### ISSUE TITLE
Getting error - Cannot find Jupyter/Colab namespace for Python

### ISSUE THREAD

**Issue by svsaraf112** [VIDA-NYU/PipelineVis#3]
I am trying to use PipelineProfiler to visualize pipelines in auto-sklearn. I am developing using docker, but I am getting the error "Cannot find Jupyter/Colab namespace for Python". Is there something that I am missing?

**Comment by jorgehpo** [comment]
Hi, are you importing PipelineProfiler from a jupyter/colab cell?
The import statement only works from these environments.

**Comment by svsaraf112** [comment]
Got it. It's resolved now. Thanks!
