### ISSUE TITLE
Colab precision

### ISSUE THREAD

**Issue by rxjx** [VIDA-NYU/PipelineVis#6]
In Colab, hyperparameter values show only two digits after the decimal which is not enough for things like tol or learning rates. Is there a way to change this?

**Comment by jorgehpo** [comment]
Hi @rxjx , that makes sense. I increased the number of decimals to 5. I plan on adding a parameter for this in the profiler call in the future, but this should fix it for now. Can you try it out using pipelineprofiler 0.1.16 ?

Closing this issue.

**Comment by rxjx** [comment]
Thanks, I'll take a look next week. I was going to suggest using the 'g' format for float parms.

**Comment by rxjx** [comment]
Definitely improved. But some parms are still zero so the 'g' format would help. Here's an example:
![image](https://user-images.githubusercontent.com/8461845/107401647-f1030b00-6ab7-11eb-87ed-1daccc2a7568.png)
